#import "./fragments/ProductFields.gql"
#import "./fragments/UserFields.gql"
query($page: Int, $size: Int, $user: String!) {
  getDiscoveredProducts(page: $page, size: $size, user: $user) {
    total
    data {
      codeCount
      ...ProductFields
      discoverer {
        ...UserFields
      }
    }
  }
}