#import "./fragments/ProductFields.gql"
#import "./fragments/UserFields.gql"
query($page: Int, $size: Int, $topic: [String!], $keyword: [String!], $state: String, $order: String, $ids: [String!]) {
  getProducts(page: $page, size: $size, topic: $topic, keyword: $keyword, state: $state, order: $order, ids: $ids) {
    total
    data {
      codeCount
      ...ProductFields
      discoverer {
        ...UserFields
      }
    }
  }
}