#import "./fragments/ProductFields.gql"
#import "./fragments/UserFields.gql"
query($page: Int, $size: Int, $score: Int, $keyword: String!) {
  searchProducts(page: $page, size: $size, score: $score, keyword: $keyword) {
    total
    data {
      codeCount
      ...ProductFields
      discoverer {
        ...UserFields
      }
    }
  }
}