#import "./fragments/UserFields.gql"
#import "./fragments/ProductFields.gql"
query UserList($page: Int, $size: Int, $isCreator: Boolean, $ids: [String!]) {
  getUsers(page: $page, size: $size, isCreator: $isCreator, ids: $ids) {
    total
    count
    page
    size
    data {
      ...UserFields
      followers {
        total
      }
      following {
        total
      }
      createdProducts {
        total
        data {
          ...ProductFields
        }
      }
    }
  }
}