#import "./fragments/ActiveFields.gql"
query UserActiveList($user: String!, $page: Int, $size: Int) {
  getUserActives(user: $user, page: $page, size: $size) {
    total
    count
    page
    size
    data {
      ...ActiveFields
    }
  }
}
