#import "./fragments/UserFields.gql"
query($id: String!, $page: Int, $size: Int) {
  user(id: $id) {
    ...UserFields
    following(page: $page, size: $size) {
      total
      data {
        ...UserFields
      }
    }
  }
}