#import "./UserFields.gql"
#import "./OptionFields.gql"
#import "./ProductFields.gql"
#import "./CommentFields.gql"
#import "./QuestionFields.gql"

fragment ActiveFields on Active {
  id
  type
  user {
    ...UserFields
  }
  createdAt
  relation {
    ... on User {
      ...UserFields
    }
    ... on Option {
      ...OptionFields
      product {
        ...ProductFields
      }
      question {
        ...QuestionFields
      }
    }
    ... on Comment {
      ...CommentFields
      user {
        ...UserFields
      }
      products {
        ...ProductFields
      }
    }
    ... on Product {
      ...ProductFields
    }
  }
}
