#import "./UserFields.gql"
#import "./ProductFields.gql"

fragment CommentFields on Comment {
  id
  content
  createdAt
  parentId
  user {
    ...UserFields
  }
  products {
    ...ProductFields
  }
}